-- AULA 25 - TIPOS DE DADOS
/* 
01 BOLEANOS(BIT): 
POR PADRÃO ELE É INICIALIZADO COMO NULO, E PODE RECEBER 1 OU 0

02 CARACTERES: 
DE TAMANHO FIXO(CHAR): PERMITE INSERIR UMA QUANTIDADE FIXA DE CARACTERES E SEMPRE OCUPA TODO O ESPAÇO RESERVADO
DE TAMANHO VARIAVEL(VARCHAR): APESAR DE TER O TAMANHO DEFINIDO SO USA O ESPAÇO QUE FOR USADO

03 NUMERICOS (VALORES EXATOS): 
NUMEROS INTEIROS(TINYINT/SMALLINT/INT/BIGINT):USADOS PARA ARMAZENAR VALORES INTERIOS
NUMERIC ou DECIMAL: VALORES EXATOS, POREM PERMITE TER PARTE FRACIONADO, QUE TAMBEM PODE SER ESPECIFICADO A PRECISÃO E ESCALDA
(ESCALA É O NUMERO DE DIGITOS NA PARTE FRACINAL) EX: NUMERIC(5,2)123,53

04 NUMERICOS (VALORES APROXIMADOS):
REAL: TEM PRECISÃO APROXIMADA DE ATE 15 DIGITOS
FLOAT: MESMO CONCEITO DO REAL

05 TEMPORAIS:
DATE: ARMAZENA A DATA NO FORMATO (aaaa/mm/dd)
DATETIME: ARMAZENA DATA E HORA (aaaa/mm/dd:hh:mm:ss)
DATETIME2: ARMAZENA DATA E HORA COM ADIÇÃO DE MILISSEGUNDOS NO FORMATO (aaaa/mm/dd:hh:mm:ss:ssss)
SMALLDATETIME: ARMAZENA DATA E HORA RESPEITANDO O LIMITE ENTRE '1900-01-01:00:00:00' ATÉ '2079-06-06:23:59:59' 
TIME: ARMAZENA HORAS, MINUTOS, SEGUNDOS E MILISSEGUNDOS RESPEITANDO OS LIMITES DE '00:00:00.000000' ATE '23:59:59.999999'
DATETIMEOFSET: PERMITE ARMAZENAR INFORMAÇOES DE DATA E HORAS INCLUINDO FUSO HORARIO

*/
